name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Restore the Dependencies
        run: npm ci
        working-directory: auto-release-draft
      - name: Build
        run: npm run all
        working-directory: auto-release-draft

